import { execSync } from "child_process";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DRAFTS_DIR = path.join(__dirname, "../stageArea/drafts");
const BLOG_DIR = path.join(__dirname, "../blog");

async function createPR() {
  // Find the latest draft
  const files = await fs.readdir(DRAFTS_DIR);
  const mdxFiles = files.filter((f) => f.endsWith(".mdx")).sort().reverse();

  if (!mdxFiles.length) {
    console.log("No drafts to publish.");
    return;
  }

  const latestDraft = mdxFiles[0];
  const draftPath = path.join(DRAFTS_DIR, latestDraft);
  const blogPath = path.join(BLOG_DIR, latestDraft);

  // Read draft content for PR description
  const content = await fs.readFile(draftPath, "utf8");
  const titleMatch = content.match(/title:\s*"(.+)"/);
  const title = titleMatch ? titleMatch[1] : latestDraft;

  // Create branch name
  const branchName = `post/${latestDraft.replace(".mdx", "")}`;

  try {
    // Make sure we're on main and up to date
    execSync("git checkout main", { stdio: "inherit" });
    execSync("git pull origin main", { stdio: "inherit" });

    // Create new branch
    execSync(`git checkout -b ${branchName}`, { stdio: "inherit" });

    // Move draft to blog folder
    await fs.copyFile(draftPath, blogPath);

    // Stage and commit
    execSync(`git add "${blogPath}"`, { stdio: "inherit" });
    execSync(`git commit -m "📝 New post: ${title}"`, { stdio: "inherit" });

    // Push branch
    execSync(`git push -u origin ${branchName}`, { stdio: "inherit" });

    // Create PR
    execSync(
      `gh pr create --title "📝 New Post: ${title}" --body "## New Blog Post

**Title:** ${title}
**File:** ${latestDraft}

---

### Review Checklist
- [ ] Content is accurate
- [ ] No typos or grammar issues
- [ ] Tags are appropriate
- [ ] Ready to publish

---

*Auto-generated by ScafBlog*" --base main`,
      { stdio: "inherit" }
    );

    // Switch back to main
    execSync("git checkout main", { stdio: "inherit" });

    // Remove from drafts after PR created
    await fs.unlink(draftPath);

    console.log(`\n✅ PR created for: ${title}`);
  } catch (err) {
    console.error("Error creating PR:", err.message);
    execSync("git checkout main", { stdio: "ignore" });
  }
}

createPR();
